// Auto-generated entity names from the scene

/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Admin_Tools = "Admin Tools",
  Beach_Rock = "Beach Rock",
  Beach_Rock_2 = "Beach Rock_2",
  Concrete_Wall_glb_4 = "Concrete_Wall.glb_4",
  Concrete_Wall_glb_6 = "Concrete_Wall.glb_6",
  Concrete_Wall_glb_7 = "Concrete_Wall.glb_7",
  Concrete_Wall_glb_8 = "Concrete_Wall.glb_8",
  Ground = "Ground",
  Invisible_Ramp = "Invisible Ramp",
  Invisible_Wall = "Invisible Wall",
  Invisible_Wall_2 = "Invisible Wall_2",
  Sandy_Rock = "Sandy Rock",
  Sandy_Rock_10 = "Sandy Rock_10",
  Sandy_Rock_11 = "Sandy Rock_11",
  Sandy_Rock_12 = "Sandy Rock_12",
  Sandy_Rock_13 = "Sandy Rock_13",
  Sandy_Rock_14 = "Sandy Rock_14",
  Sandy_Rock_15 = "Sandy Rock_15",
  Sandy_Rock_16 = "Sandy Rock_16",
  Sandy_Rock_2 = "Sandy Rock_2",
  Sandy_Rock_4 = "Sandy Rock_4",
  Sandy_Rock_5 = "Sandy Rock_5",
  Sandy_Rock_6 = "Sandy Rock_6",
  Sandy_Rock_7 = "Sandy Rock_7",
  Sandy_Rock_8 = "Sandy Rock_8",
  Sandy_Rock_9 = "Sandy Rock_9",
  Tile_1 = "Tile 1",
  Tile_2 = "Tile 2",
  Tile_3 = "Tile 3",
  Tile_4 = "Tile 4",
  Tile_5 = "Tile 5",
  Tile_6 = "Tile 6",
  Tile_7 = "Tile 7",
  Tile_8 = "Tile 8",
  Tile_9 = "Tile 9",
  Video_Screen = "Video Screen",
  baitshop1_glb = "baitshop1.glb",
  pinkt3_glb_2 = "pinkt3.glb_2",
  pinkt3_glb_3 = "pinkt3.glb_3",
  pinkt3_glb_4 = "pinkt3.glb_4",
  pinkt3_glb_5 = "pinkt3.glb_5",
  stage_cleaned_with_colliders_glb = "stage_cleaned_with_colliders.glb",
  waterreal_glb_2 = "waterreal.glb_2",
  waterreal_glb_3 = "waterreal.glb_3"
}
